### ISSUE TITLE
Packaging needs to add a conflict for pulseaudio-module-bluetooth

### ISSUE THREAD

**Issue by mmstick** [pipewire-debian/pipewire-debian#17]
This will fix the issue of being unable to connect to bluetooth devices.

**Comment by souravdas142** [comment]
Sorry, I did not get it, do you need this feature for this package only or you want this feature for PipeWire project? If you want this feature for PipeWire project, may be its a good idea to create a feature request issue at [upstream issue](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues), Other peoples can  get benefited from this also.

**Comment by mmstick** [comment]
This is a packaging repository, is it not?

**Comment by souravdas142** [comment]
Sorry man... I got it. Actually I didn't know there is a package name `pulseaudio-module-bluetooth` available, I am usally a Arch user, have `pulseaudio-bluetooth` instead. 

I will be checked and updating the package according to the requirements. And thank you.

**Comment by pipewire-debian** [comment]
But PipeWire and PulseAudio doesn't have their moudle base different? Can you please give some instruction how to reproduce any error if both have installed? @mmstick

**Comment by souravdas142** [comment]
done @mmstick should i need to release it now under launchpad or wait for 0.3.30 (expected on 18 june)?

**Comment by mmstick** [comment]
That's up to you.

**Comment by souravdas142** [comment]
Thank you again. I will be releasing this change in 0.3.30.

**Comment by alexzeitgeist** [comment]
@mmstick just curious, do you have a reference to potential issues with connecting to bluetooth devices due to the pulseaudio-module-bluetooth package? Installing or upgrading to Pipewire 0.3.30 now essentially means modifying an existing pulseaudio installation, meaning, if someone was to uninstall Pipewire again, he'd have to remember to reinstall the removed pulseaudio-module-bluetooth package.

I've been running Pipewire extensively along with an existing Pulseaudio installation on Ubuntu 21.04 and haven't noticed any problems connecting to Bluetooth devices.

**Comment by souravdas142** [comment]
> @mmstick just curious, do you have a reference to potential issues with connecting to bluetooth devices due to the pulseaudio-module-bluetooth package? Installing or upgrading to Pipewire 0.3.30 now essentially means modifying an existing pulseaudio installation, meaning, if someone was to uninstall Pipewire again, he'd have to remember to reinstall the removed pulseaudio-module-bluetooth package.
> 
> I've been running Pipewire extensively along with an existing Pulseaudio installation on Ubuntu 21.04 and haven't noticed any problems connecting to Bluetooth devices.

@alexzeitgeist  yeah the same question https://github.com/pipewire-debian/pipewire-debian/issues/17#issuecomment-855198074 @mmstick  Arch Linux also doing it. But their aim is to replace pulseaudio with pipewire? I can find 2 issues regarding on it on upstream  [#489](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/489) and [#575](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/575) but I still couldn't understand why its require except replacing.

But this package doesn't aim to replace anything but aims to install pipewire and pulseaudio side by side and user can switch between then any time quickly.

**Comment by alexzeitgeist** [comment]
@souravdas142 yeah Arch Linux is probably a bit different in this regard. I am still not sure about pulseaudio-module-bluetooth though. It didn't cause any issues for me, and I have been using pipewire extensively along with all kinds of Bluetooth devices, and as far as I know, pulseaudio-module-bluetooth only contains a handful of pulse modules anyhow. Perhaps the existence of these modules confuses bluez? Not sure. That's why I asked if there were any references that would explain the issue.

**Comment by souravdas142** [comment]
@alexzeitgeist Let the @memstick give the ans. He is an senior pop_os developer. May be he has a valid reason to suggest this. But we just still need an valid reproducible bugs/issue that reference this otherwise I'll be reverted 74749fb951bb9c6ce41623b4c171ef88ec913433  for now

**Comment by mmstick** [comment]
It's not possible to connect to Bluetooth audio devices with that package installed. It's for this reason that the official Debian wiki mentions to remove this package when setting up Pipewire: https://wiki.debian.org/PipeWire#Bluetooth

I get a "Protocol not available" message when trying to connect to any Bluetooth audio devices with this package installed. Only on removal and a restart of the services does Bluetooth function.

**Comment by alexzeitgeist** [comment]
Thanks for the explanation. That's odd, and is possibly related to the specific package versions used in the Debian release, in which case removing the package might be the easiest solution if that helps. 🤷

I would have liked to see another solution as this conflict resolution in the packaging essentially breaks part of an existing pulseaudio installation if the user chooses to install or upgrade pipewire. It's probably advisable to note it in the Wiki. 

FWIW, on my side, running Ubuntu 21.04 with stock pulseaudio disabled but not uninstalled, and with pipewire started from systemd user units, there are no issues with that package installed; connecting to Bluetooth audio devices works very reliably (using all kinds of Bluetooth codecs from sbc, aac to ldac).

**Comment by mmstick** [comment]
An alternative could be creating a dummy package, rather than adding a conflict. The dummy package would simply be an empty package that effectively removes the PulseAudio package, but keeps that dependency in the system so you can safely downgrade when purging the PPA at a later date.

I'm using Pop!_OS 21.04, but we use all the same packages as Ubuntu, so behavior should be the same regarding PulseAudio. All I can say that that I installed this from a PPA to test out how far along Pipewire is as a drop-in replacement to PulseAudio, but struggled with a protocol not available error until finally removing that package after reading that wiki.

**Comment by souravdas142** [comment]
@mmstick  From `Debian wiki`

> Please note that this is a crude hack and if thoughtlessly used, it might possibly do damage to your packaging system. And please note as well that using it is not the recommended way of dealing with broken dependencies. Better file a bug report instead. For more, see [this](https://wiki.debian.org/Packaging/HackingDependencies)

as it says it may damage packaging system, should we still need to do it?

> but keeps that dependency in the system so you can safely downgrade when purging the PPA at a later date.

To make work everything again with `PulseAudio` , you have to purge this PPA right? But the goal of this package : PipeWire and PulseAudio installed side by side and If a upgrade for the PIpeWire breaks something, Users can quickly switch to PulseAudio without installing or uninstalling anything. Perhaps `pipewire-pulse` should conflicts with `pulseaudio-module-bluetooth` according to  [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/619#note_826881) upstream issue, but still problem is not reproducible with my machine having installed ubuntu 20.04. I am still quite unsure about the whole thing.

> I would have liked to see another solution as this conflict resolution in the packaging essentially breaks part of an existing pulseaudio installation if the user chooses to install or upgrade pipewire. It's probably advisable to note it in the Wiki.


Plus If we tell users mentioning brief of this issue at installation time (ofcourse in a postinst, postrm script) and tell users in the brief that if they occured any problem with bluetooth connection or audio profile switching, remove `pulseaudo-module-bluetooth`? this will give users a chance of choosing things? I think we need more user's feedback regarding this?

**Comment by alexzeitgeist** [comment]
> I'm using Pop!_OS 21.04, but we use all the same packages as Ubuntu, so behavior should be the same regarding PulseAudio. All I can say that that I installed this from a PPA to test out how far along Pipewire is as a drop-in replacement to PulseAudio, but struggled with a protocol not available error until finally removing that package after reading that wiki.

Interesting. Did you perhaps install another port of pulseaudio in the past? I just found [this bug report](https://bugs.launchpad.net/ubuntu/+source/pipewire/+bug/1917800) from March 04 describing your issue; it was then deemed invalid by the OP. The [Debian Wiki entry](https://wiki.debian.org/PipeWire?action=diff&rev2=12&rev1=11) was added on May 12, but without a reference.

Either way, I don't think I am ever going back to pulseaudio; so personally, I don't care about uninstalling the package. 😉

**Comment by souravdas142** [comment]
I still can't reproduce the bug on a fresh install of ubuntu 20.04. PA and PW and all of their modules installed side by side. though I have not any hardware to test LDAC or APTX but I can connect all profiles [ HFP (A2DP Sink, codec AAC), HFP (A2DP Sink), HFP (A2DP Sink, codec SBC), HSP/HFP,  HSP/HFP (Codec CVSD) ] without any error you mentioned @mmstick  , @alexzeitgeist  confirms he can connect all profiles without any error https://github.com/pipewire-debian/pipewire-debian/issues/17#issuecomment-859086349 this included LDAC and APTX codec. 

@mmstick can you please guide me to reproduce any error you mentioned ?

@alexzeitgeist  I think problem was valid, If not so then why others people were effected? see upstream [issue here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/619#note_826881) and may be with time its resolved. If not so everyone can reproduce the problem then? is it not? Lastly , 

> I am ever going back to pulseaudio; so personally, I don't care about uninstalling the package

But may be everyone is not so bold like you, Ubuntu users are lot of complaing about a small change. Thank you for the decession But please help this package to get rid of this issue (I mean whether  should I conflict or not?).

**Comment by alexzeitgeist** [comment]
> @alexzeitgeist I think problem was valid, If not so then why others people were effected? see upstream [issue here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/619#note_826881) and may be with time its resolved. If not so everyone can reproduce the problem then? is it not? 

It's actually one and the same person who made the upstream post and the bug report, which was later closed as invalid.  In his words, "[i]t seems like other folks dont have this issue. I think I had pulseaudio-modules-bt (from a PPA) at some point. Maybe that has messed up my configuration, not this package...".

**Comment by souravdas142** [comment]
**No, I can't reproduce any error from ubuntu 21.04 also.** 

> It's actually one and the same person who made the upstream post and the bug report, which was later closed as invalid. In his words, "[i]t seems like other folks dont have this issue. I think I had pulseaudio-modules-bt (from a PPA) at some point. Maybe that has messed up my configuration, not this package...".

Yeah right you are. lets wait for the reply from @mmstick .

If everything is ok without conflicting, I'll be waiting to hear from more people and for now will be removing the conflicted package. If users complaing same like this issue, I'll think then about it. For now I'll be writing this on `Troubleshooting` page and probably showing users a message about the issue in a `post{inst,rm}` script, the script will be running while installing or removing the package.

**Comment by souravdas142** [comment]
Tomorrow I'll be releasing 2nd patch for this package with the changes upto this.

**Comment by souravdas142** [comment]
**Some Update -** A reddit user on void linux had this problem on 0.3.21, he had to install `libspa-bluetooth` to fix it without uninstalling anything. For all debian or its derivatives, installing the relevant pipewire bluetooth package should fix the problem.  Here is the [source](https://www.reddit.com/r/linuxquestions/comments/led200/bluetooth_headset_wont_connect_after_installing/), also checkout [this one](https://atish3604.medium.com/solved-bluetooth-headset-mic-not-working-detected-in-ubuntu-20-04-86a5236444d0)

**Still I'll keep this issue opened upto 1 more PW release, If no one report back till then I'll be closed this.**

**Comment by souravdas142** [comment]
@mmstick  see https://www.reddit.com/r/pop_os/comments/ofdalv/replaced_pulseaudio_with_pipewire_on_popos_2104_i 

They are using pipewire without uninstalling `pulseaudio-module-bluetooth` and no one reporting they have any issue over bluetooth or something else. Also you should consider this issue has been opened for almost 37 days and no one except you has been reported back. So I'm closing it.           

**If Anyone come to this issue, they should consider this as `MISLEADING` and should avoid this**                   

They should not occurred any problem for `pulseaudio-module-bluetooth`. Thanks.

**Comment by VladStulikov** [comment]
Not misleading, the issue still exists. I am running a fresh Debian 12 installation and my headphones did not connect until I removed the "pulseaudio-module-bluetooth" package. I did not install the package by myself, it was installed by Debian. Spent hours figuring it out. 
Another way to sole it was to downgrade bluez to the bullseye' 5.55, the version has no conflict with "pulseaudio-module-bluetooth" but default in bookworm 5.66 still conflicts with the package
