### ISSUE TITLE
Linux Mint instalation - missing Release a InRelease files

### ISSUE THREAD

**Issue by jirkace** [pipewire-debian/pipewire-debian#5]
**Describe the bug**
```
Ign:14 https://pipewire-debian.github.io/pipewire-debian ./ InRelease                                                                   
Err:15 https://pipewire-debian.github.io/pipewire-debian ./ Release                                             
  404  Not Found [IP: 185.199.108.153 443]
```

**To Reproduce**
```
curl -SsL https://pipewire-debian.github.io/pipewire-debian/ubuntu/KEY.gpg | sudo apt-key add -
sudo curl -SsL -o /etc/apt/sources.list.d/pipewire.list https://pipewire-debian.github.io/pipewire-debian/ubuntu/pipewire.list
sudo apt update
```

I tries also this Github repo as path in sources list, but it failed too - for another error (sorry for Czech language in console output, but you will definitely understand)
```
Stahuje se:13 https://github.com/pipewire-debian/pipewire-debian/tree/master/ubuntu ./ InRelease   
Err:13 https://github.com/pipewire-debian/pipewire-debian/tree/master/ubuntu ./ InRelease
  Podepsaný soubor není platný, obdrženo „NOSPLIT“ (vyžaduje přístup na síť ověření?)
Načítají se seznamy balíků… Hotovo
E: Selhalo stažení https://github.com/pipewire-debian/pipewire-debian/tree/master/ubuntu/./InRelease  Podepsaný soubor není platný, obdrženo „NOSPLIT“ (vyžaduje přístup na síť ověření?)
E: Repositář „https://github.com/pipewire-debian/pipewire-debian/tree/master/ubuntu ./ InRelease“ není podepsán.
N: Aktualizaci z takového repositáře nelze provést zabezpečeně a je proto implicitně zakázána.
N: Podrobnosti o vytváření a nastavení repositářů naleznete v manuálové stránce apt-secure(8).
```

**Expected behavior**
APT will update repository without error :-)

**Screenshots**
```
-> cat /etc/apt/sources.list.d/pipewire.list
deb https://pipewire-debian.github.io/pipewire-debian ./
```

**Desktop (please complete the following information):**
 - Distro: Linux Mint
 - Desktop Environment Gnome
 - Version 20.1 (ulyssa)

**Comment by souravdas142** [comment]
sorry for the issue. edit `/etc/apt/sources.list.d/pipewire.list` and append `/ubuntu` at the end of the repo `url`   
or issue : `echo "deb https://pipewire-debian.github.io/pipewire-debian/ubuntu ./" | sudo tee /etc/apt/sources.list.d/pipewire.list`   
problem should be solved.

Actually I recently cleaednup this repo, and moved all packages to `ubuntu/` this is why the problem occurred.
You may fail to install pipewire from launchpad for now, because **`PipeWire 0.3.27`** released, and is in building queue under launchpad.  It may take 2~4 hours to fix for launchpad.

**Comment by jirkace** [comment]
Thank you for your quick reply, now I have installed pipewire and all dependencies successfully.

I want to try Pipewire, because when I'm using bluetooth headset with mic, the sound quality is very poor. But... so...  current configuration with Pipewire didn't solve my problem :-(
Now I can choose one of profiles:
- High Fidelity Playback (A2DP Sink)
- High Fidelity Playback (A2DP Sink, codec SBC)
- High Fidelity Playback (A2DP Sink, codec AAC)
- Headset Head Unit (HSP/HFP)
- Headset Head Unit (HSP/HFP, codec CVSD)

When I choose any profile with AD2P, sound quality is great, but system select internal mic. When I switch to headset mic, the profile is automaticaly switched to HSP/HFP and sound quality is not so good :-( 

Can you please guide me, what am I doing wrong?

```
-> pactl info
Nastavení serveru: /run/user/1001/pulse/native
Verze knihovního protokolu: 33
Verze serverového protokolu: 35
Je místní: ano
Index klienta: 52
Velikost dlaždice: 65472
Uživatelské jméno: blackie
Název hostitele: blackie-pc
Název serveru: PulseAudio (on PipeWire 0.3.27)
Verze serveru: 14.0.0
Výchozí specifikace vzorku: float32le 2 ch 48000 Hz
Výchozí mapa kanálů: front-left,front-right
Výchozí cíl: bluez_output.10_29_30_00_02_7C.a2dp-sink
Výchozí zdroj: alsa_input.pci-0000_00_1f.3.analog-stereo
Cookie: d4d4:ce81
```

```
-> systemctl --user status pipewire{,-pulse}.{socket,service} pipewire-media-session.service
● pipewire.socket - Multimedia System
     Loaded: loaded (/usr/lib/systemd/user/pipewire.socket; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-05-06 23:13:50 CEST; 34min ago
   Triggers: ● pipewire.service
     Listen: /run/user/1001/pipewire-0 (Stream)
     CGroup: /user.slice/user-1001.slice/user@1001.service/pipewire.socket

kvě 06 23:13:50 blackie-pc systemd[2500]: Listening on Multimedia System.

● pipewire.service - Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-05-06 23:13:50 CEST; 34min ago
TriggeredBy: ● pipewire.socket
   Main PID: 2509 (pipewire)
     CGroup: /user.slice/user-1001.slice/user@1001.service/session.slice/pipewire.service
             └─2509 /usr/bin/pipewire

kvě 06 23:15:37 blackie-pc pipewire[2509]: (bluez_output.10_29_30_00_02_7C.a2dp-sink-52) client too slow! rate:512/48000 pos:518912 status:triggered
kvě 06 23:15:37 blackie-pc pipewire[2509]: (bluez_output.10_29_30_00_02_7C.a2dp-sink-52) client too slow! rate:512/48000 pos:518912 status:triggered
kvě 06 23:15:51 blackie-pc pipewire[2509]: 4 events suppressed
kvě 06 23:15:51 blackie-pc pipewire[2509]: (bluez_output.10_29_30_00_02_7C.a2dp-sink-52) client too slow! rate:512/48000 pos:1202944 status:triggered
kvě 06 23:15:51 blackie-pc pipewire[2509]: (bluez_output.10_29_30_00_02_7C.a2dp-sink-52) client too slow! rate:512/48000 pos:1202944 status:triggered
kvě 06 23:20:42 blackie-pc pipewire[2509]: (bluez_input.10_29_30_00_02_7C.headset-head-unit-59) client too slow! rate:864/48000 pos:216864 status:triggered
kvě 06 23:20:42 blackie-pc pipewire[2509]: (bluez_input.10_29_30_00_02_7C.headset-head-unit-59) client too slow! rate:864/48000 pos:216864 status:triggered
kvě 06 23:20:42 blackie-pc pipewire[2509]: (cinnamon-84) client too slow! rate:864/48000 pos:216864 status:triggered
kvě 06 23:20:42 blackie-pc pipewire[2509]: (cinnamon-88) client too slow! rate:864/48000 pos:216864 status:triggered
kvě 06 23:36:19 blackie-pc pipewire[2509]: 1 events suppressed

● pipewire-pulse.socket - PipeWire PulseAudio
     Loaded: loaded (/usr/lib/systemd/user/pipewire-pulse.socket; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-05-06 23:13:50 CEST; 34min ago
   Triggers: ● pipewire-pulse.service
     Listen: /run/user/1001/pulse/native (Stream)
     CGroup: /user.slice/user-1001.slice/user@1001.service/pipewire-pulse.socket

kvě 06 23:13:50 blackie-pc systemd[2500]: Listening on PipeWire PulseAudio.

● pipewire-pulse.service - PipeWire PulseAudio
     Loaded: loaded (/usr/lib/systemd/user/pipewire-pulse.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-05-06 23:13:50 CEST; 34min ago
TriggeredBy: ● pipewire-pulse.socket
   Main PID: 2511 (pipewire-pulse)
     CGroup: /user.slice/user-1001.slice/user@1001.service/session.slice/pipewire-pulse.service
             └─2511 /usr/bin/pipewire-pulse

kvě 06 23:13:50 blackie-pc systemd[2500]: Started PipeWire PulseAudio.
kvě 06 23:37:36 blackie-pc pipewire-pulse[2511]: 'CHECK_PORT(this, direction, port_id)' failed at ../spa/plugins/audioconvert/merger.c:1004 impl_node_port_set_param()
kvě 06 23:37:36 blackie-pc pipewire-pulse[2511]: node 0x560cf00cc3e0: error unset format output: Invalid argument

● pipewire-media-session.service - Multimedia Service Session Manager
     Loaded: loaded (/usr/lib/systemd/user/pipewire-media-session.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-05-06 23:13:50 CEST; 34min ago
   Main PID: 2510 (pipewire-media-)
     CGroup: /user.slice/user-1001.slice/user@1001.service/session.slice/pipewire-media-session.service
             └─2510 /usr/bin/pipewire-media-session

kvě 06 23:13:50 blackie-pc systemd[2500]: Started Multimedia Service Session Manager.
kvě 06 23:13:55 blackie-pc pipewire-media-session[2510]: bluez5-monitor: Failed to register battery provider. Error: org.freedesktop.DBus.Error.UnknownMethod
kvě 06 23:13:55 blackie-pc pipewire-media-session[2510]: bluez5-monitor: BlueZ Battery Provider is not available, won't retry to register it. Make sure you are running BlueZ 5.56+ with experimental features to use Battery Provider.
kvě 06 23:20:42 blackie-pc pipewire-media-session[2510]: (bluez_input.10_29_30_00_02_7C.headset-head-unit-19) client missed 1 wakeups
kvě 06 23:20:51 blackie-pc pipewire-media-session[2510]: native: connect(): Software caused connection abort. Remaining retry:1
kvě 06 23:35:07 blackie-pc pipewire-media-session[2510]: native: connect(): Software caused connection abort. Remaining retry:1
```


```
-> systemctl status bluetooth.service
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-05-06 23:13:40 CEST; 37min ago
       Docs: man:bluetoothd(8)
   Main PID: 1173 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 37982)
     Memory: 5.5M
     CGroup: /system.slice/bluetooth.service
             └─1173 /usr/lib/bluetooth/bluetoothd

kvě 06 23:50:23 blackie-pc bluetoothd[1173]: Endpoint unregistered: sender=:1.59 path=/MediaEndpoint/A2DPSink/sbc
kvě 06 23:50:23 blackie-pc bluetoothd[1173]: Endpoint unregistered: sender=:1.59 path=/MediaEndpoint/A2DPSource/sbc
kvě 06 23:50:23 blackie-pc bluetoothd[1173]: Endpoint registered: sender=:1.108 path=/MediaEndpoint/A2DPSource/ldac
kvě 06 23:50:23 blackie-pc bluetoothd[1173]: Endpoint registered: sender=:1.108 path=/MediaEndpoint/A2DPSink/aptx_hd
kvě 06 23:50:23 blackie-pc bluetoothd[1173]: Endpoint registered: sender=:1.108 path=/MediaEndpoint/A2DPSource/aptx_hd
kvě 06 23:50:23 blackie-pc bluetoothd[1173]: Endpoint registered: sender=:1.108 path=/MediaEndpoint/A2DPSink/aptx
kvě 06 23:50:23 blackie-pc bluetoothd[1173]: Endpoint registered: sender=:1.108 path=/MediaEndpoint/A2DPSource/aptx
kvě 06 23:50:23 blackie-pc bluetoothd[1173]: Endpoint registered: sender=:1.108 path=/MediaEndpoint/A2DPSource/aac
kvě 06 23:50:23 blackie-pc bluetoothd[1173]: Endpoint registered: sender=:1.108 path=/MediaEndpoint/A2DPSink/sbc
kvě 06 23:50:23 blackie-pc bluetoothd[1173]: Endpoint registered: sender=:1.108 path=/MediaEndpoint/A2DPSource/sbc
```

**Comment by souravdas142** [comment]
I think, Its normal, I'm using PW since 0.3.22 on my native Arch linux, It behaves the same way you described. please read [wiki section](https://github.com/pipewire-debian/pipewire-debian/wiki#book-wiki) and [Troubleshooting](https://github.com/pipewire-debian/pipewire-debian/wiki/Troubleshooting) page and consult with this [page](https://gitlab.freedesktop.org/jasker5183/test/-/blob/master/Advanced%20Configuration.md) also. If you have any problem regarding on pipewire but this ppa, create a issue [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues). **Search your topic before creating any new issue.**

**Comment by jirkace** [comment]
Once more, thank you! :-)
